import 'package:flutter/material.dart';

class Banio {
  final String image, title,imagen,mostrar,correcta;
  final int size, id;
  final Color color;
  final List<String> opciones,imagenes;
  Banio({
    this.id,
    this.image,
    this.title,
    this.size,
    this.color,
    this.imagen,
    this.mostrar,
    this.imagenes,
    this.opciones,
    this.correcta
  });
}
List<Banio> objetos = [
  Banio(
      id: 1,
      title: "Cepillo Dental",
      size: 12,
      image: "assets/images/banio/cepillo.png",
      color: Color(0xFF3D82AE),
      imagen: "assets/images/banio/accion/1.jpg",
      mostrar: "Pedro usa un -- para lavarse los dientes",
      opciones: [
        "manzana",
        "jabon",
        "cobija",
        "taza",
        "plato",
        "cepillo dental",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "cepillo dental",
  ),
  Banio(
      id: 2,
      title: "Inodoro",
      size: 8,
      image: "assets/images/banio/inodoro.png",
      color: Color(0xFFD3A984),
      imagen: "assets/images/banio/accion/2.jpg",
      mostrar: "En el baño hay un --",
      opciones: [
        "brocoli",
        "pasta dental",
        "inodoro",
        "taza",
        "plato",
        "fresa",
      ],
      imagenes: [
        "assets/images/cocina/brocoli.png",
        "assets/images/banio/pasta.png",
        "assets/images/banio/inodoro.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/fresa.png",
      ],
      correcta: "inodoro",
  ),
  Banio(
      id: 3,
      title: "Jabon",
      size: 10,
      image: "assets/images/banio/jabon.png",
      color: Color(0xFF989493),
      imagen: "assets/images/banio/accion/3.jpg",
      mostrar: "Dany se lava sus manos con --",
      opciones: [
        "platano",
        "jabon",
        "almohada",
        "taza",
        "plato",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/platano.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/almohada.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "jabon",
  ),
  Banio(
      id: 4,
      title: "Labavo",
      size: 11,
      image: "assets/images/banio/labavo.png",
      color: Color(0xFFE6B398),
      imagen: "assets/images/banio/accion/4.jpg",
      mostrar: "Ramon se lava su cara en el --",
      opciones: [
        "lechuga",
        "cama",
        "lavabo",
        "taza",
        "platano",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/lechuga.png",
        "assets/images/recamara/cama.png",
        "assets/images/banio/labavo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/platano.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "lavabo",
  ),
  Banio(
      id: 5,
      title: "Pasta Dental",
      size: 28,
      image: "assets/images/banio/pasta.png",
      color: Color(0xFFFB7883),
      imagen: "assets/images/banio/accion/5.png",
      mostrar: "Adrian usa -- para lavar sus dientes.",
      opciones: [
        "manzana",
        "jabon",
        "lampara",
        "taza",
        "pasta dental",
        "espejo",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/espejo.png",
      ],
      correcta: "pasta dental",
  ),
  Banio(
    id: 6,
    title: "Shampoo",
    size: 12,
    image: "assets/images/banio/shampoo.png",
    color: Color(0xFFAEAEAE),
    imagen: "assets/images/banio/accion/6.png",
    mostrar: "Sara se lava el cabello con --",
    opciones: [
      "uva",
      "shampoo",
      "cobija",
      "taza",
      "plato",
      "cuchara",
    ],
    imagenes: [
      "assets/images/cocina/uva.png",
      "assets/images/banio/shampoo.png",
      "assets/images/recamara/cobertor.png",
      "assets/images/cocina/taza.png",
      "assets/images/cocina/plato.png",
      "assets/images/cocina/cuchara.png",
    ],
    correcta: "shampoo",
  ),
];

