import 'package:flutter/material.dart';

class Cocina {
  final String image,
      title,
      imagen,
      mostrar,
      correcta,
      imgcorrecta,
      objeto,
      frase,
      imglugar,
      lugar;
  final int size, id, validos;
  final Color color;
  final List<String> opciones, imagenes, imagenes2, imagenes3;
  Cocina(
      {this.id,
        this.image,
        this.title,
        this.size,
        this.color,
        this.imagen,
        this.mostrar,
        this.imagenes,
        this.imagenes2,
        this.imagenes3,
        this.validos,
        this.lugar,
        this.frase,
        this.imglugar,
        this.opciones,
        this.imgcorrecta,
        this.objeto,
        this.correcta});
}

List<Cocina> objetos = [
  Cocina(
      id: 1,
      title: "Estufa",
      size: 12,
      image: "assets/images/cocina/estufa.png",
      color: Color(0xFF01A2C6),
      imagen: "assets/images/cocina/accion/1.png",
      mostrar: "Rosita cocina en la --",
      opciones: [
        "cazuela",
        "jabon ",
        "cobija",
        "taza",
        "plato",
        "estufa",
        "cepillo"
      ],
      imagenes: [
        "assets/images/cocina/cazuela.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/estufa.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "estufa",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "la estufa",
      imgcorrecta: "estufa",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/banio/cepillo.png--cepillo--bano",
        "assets/images/cocina/estufa.png--estufa--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 2,
      title: "Cazuela",
      size: 8,
      image: "assets/images/cocina/cazuela.png",
      color: Color(0xFFD15A05),
      imagen: "assets/images/cocina/accion/2.jpg",
      mostrar: "Pedro está comiendo un --",
      opciones: [
        "vaso",
        "jabon ",
        "cazuela",
        "taza",
        "plato",
        "estufa",
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/banio/jabon.png",
        "assets/images/cocina/cazuela.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/estufa.png",
      ],
      correcta: "cazuela",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/vaso.png--vaso",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/armario.png--armario",
        "assets/images/cocina/cazuela.png--cazuela",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "la cazuela",
      imgcorrecta: "cazuela",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/vaso.png--vaso--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/banio/inodoro.png--inodoro--bano",
        "assets/images/cocina/mesa.png--mesa--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 3,
      title: "Vaso",
      size: 10,
      image: "assets/images/cocina/vaso.png",
      color: Color(0xFF953d68),
      imagen: "assets/images/cocina/accion/3.jpg",
      mostrar: "El -- de Ana",
      opciones: [
        "mesa",
        "jabon ",
        "lavabo",
        "taza",
        "vaso",
        "estufa",
      ],
      imagenes: [
        "assets/images/cocina/mesa.png",
        "assets/images/banio/jabon.png",
        "assets/images/banio/labavo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/vaso.png",
        "assets/images/cocina/estufa.png",
      ],
      correcta: "vaso",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/taza.png--taza",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/vaso.png--vaso",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/banio/jabon.png--jabon",
      ],
      objeto: "el vaso",
      imgcorrecta: "vaso",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/taza.png--taza--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/banio/pasta.png--pasta--bano",
        "assets/images/cocina/mesa.png--mesa--cocina",
        "assets/images/cocina/vaso.png--vaso--cocina",
      ],
      validos: 4,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 4,
      title: "Mesa",
      size: 11,
      image: "assets/images/cocina/mesa.png",
      color: Color(0xFFf9AC34),
      imagen: "assets/images/cocina/accion/4.png",
      mostrar: "Adrian tiene una --",
      opciones: [
        "vaso",
        "pasta dental",
        "cobija",
        "taza",
        "mesa",
        "estufa",
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/mesa.png",
        "assets/images/cocina/estufa.png",
      ],
      correcta: "mesa",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/cama.png--cama",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/banio/labavo.png--lavabo",
      ],
      objeto: "la mesa",
      imgcorrecta: "mesa",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/mesa.png--mesa--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/banio/pasta.png--pasta--bano",
        "assets/images/cocina/estufa.png--estufa--cocina",
        "assets/images/banio/shampoo.png--shampoo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 5,
      title: "Taza",
      size: 28,
      image: "assets/images/cocina/taza.png",
      color: Color(0xFFad2c34),
      imagen: "assets/images/cocina/accion/5.jpg",
      mostrar: "Teresa esta comiendo un --",
      opciones: [
        "vaso",
        "jabon ",
        "armario",
        "tomate",
        "plato",
        "estufa",
        "taza"
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/armario.png",
        "assets/images/cocina/tomate.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/estufa.png",
        "assets/images/cocina/taza.png",
      ],
      correcta: "taza",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/cazuela.png--cazuela",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "la taza",
      imgcorrecta: "taza",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/taza.png--taza--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/banio/cepillo.png--inodoro--bano",
        "assets/images/banio/labavo.png--lavabo--bano",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 6,
      title: "Plato",
      size: 12,
      image: "assets/images/cocina/plato.png",
      color: Color(0xFF205134),
      imagen: "assets/images/cocina/accion/6.jpg",
      mostrar: "En la mesa hay un --",
      opciones: [
        "vaso",
        "toalla",
        "lampara",
        "taza",
        "plato",
        "cazuela",
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/banio/toalla.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/cazuela.png",
      ],
      correcta: "plato",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "el plato",
      imgcorrecta: "plato",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/vaso.png--vaso--cocina",
        "assets/images/banio/cepillo.png--inodoro--bano",
        "assets/images/cocina/mesa.png--mesa--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
        "assets/images/cocina/plato.png--plato--cocina",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
];