import 'package:flutter/material.dart';

class Cocina {
  final String image,
      title,
      imagen,
      mostrar,
      correcta,
      imgcorrecta,
      objeto,
      frase,
      imglugar,
      lugar;
  final int size, id, validos;
  final Color color;
  final List<String> opciones, imagenes, imagenes2, imagenes3;
  Cocina(
      {this.id,
        this.image,
        this.title,
        this.size,
        this.color,
        this.imagen,
        this.mostrar,
        this.imagenes,
        this.imagenes2,
        this.imagenes3,
        this.validos,
        this.lugar,
        this.frase,
        this.imglugar,
        this.opciones,
        this.imgcorrecta,
        this.objeto,
        this.correcta});
}

List<Cocina> objetos = [
  Cocina(
      id: 1,
      title: "Uva",
      size: 12,
      image: "assets/images/cocina/uva.png",
      color: Color(0xFF3D82AE),
      imagen: "assets/images/cocina/accion/1.png",
      mostrar: "Rosita come --",
      opciones: [
        "manzana",
        "jabon ",
        "cobija",
        "taza",
        "plato",
        "uvas",
        "cepillo"
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "uvas",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/uva.png--uvas",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "las uvas",
      imgcorrecta: "uvas",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/banio/cepillo.png--cepillo--bano",
        "assets/images/cocina/uva.png--uvas--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 2,
      title: "Brocoli",
      size: 8,
      image: "assets/images/cocina/brocoli.png",
      color: Color(0xFFD3A984),
      imagen: "assets/images/cocina/accion/2.jpg",
      mostrar: "Pedro está comiendo un --",
      opciones: [
        "manzana",
        "jabon ",
        "brocoli",
        "taza",
        "plato",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/cocina/brocoli.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "brocoli",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/manzana.png--manzana",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/armario.png--armario",
        "assets/images/cocina/brocoli.png--brocoli",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "el brocoli",
      imgcorrecta: "brocoli",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/cuchara.png--cuchara--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/banio/inodoro.png--inodoro--bano",
        "assets/images/cocina/fresa.png--fresa--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 3,
      title: "Cuchara",
      size: 10,
      image: "assets/images/cocina/cuchara.png",
      color: Color(0xFF989493),
      imagen: "assets/images/cocina/accion/3.jpg",
      mostrar: "La -- de Ana",
      opciones: [
        "fresa",
        "jabon ",
        "lavabo",
        "taza",
        "cuchara",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/fresa.png",
        "assets/images/banio/jabon.png",
        "assets/images/banio/labavo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/cuchara.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "cuchara",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/platano.png--platano",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/cuchara.png--cuchara",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/jabon.png--jabon",
      ],
      objeto: "la cuchara",
      imgcorrecta: "cuchara",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/platano.png--platano--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/banio/pasta.png--pasta--bano",
        "assets/images/cocina/fresa.png--fresa--cocina",
        "assets/images/cocina/taza.png--taza--cocina",
      ],
      validos: 4,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 4,
      title: "Fresa",
      size: 11,
      image: "assets/images/cocina/fresa.png",
      color: Color(0xFFE6B398),
      imagen: "assets/images/cocina/accion/4.png",
      mostrar: "Adrian tiene una --",
      opciones: [
        "manzana",
        "pasta dental",
        "cobija",
        "taza",
        "fresa",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/fresa.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "fresa",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/cama.png--cama",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/labavo.png--lavabo",
      ],
      objeto: "la fresa",
      imgcorrecta: "fresa",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/fresa.png--fresa--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/banio/pasta.png--pasta--bano",
        "assets/images/cocina/uva.png--uvas--cocina",
        "assets/images/banio/shampoo.png--shampoo--bano",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 5,
      title: "Platano",
      size: 28,
      image: "assets/images/cocina/platano.png",
      color: Color(0xFFFB7883),
      imagen: "assets/images/cocina/accion/5.jpg",
      mostrar: "Teresa esta comiendo un --",
      opciones: [
        "manzana",
        "jabon ",
        "armario",
        "tomate",
        "plato",
        "uva",
        "platano"
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/armario.png",
        "assets/images/cocina/tomate.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
        "assets/images/cocina/platano.png",
      ],
      correcta: "platano",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/platano.png--platano",
        "assets/images/cocina/taza.png--taza",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "el platano",
      imgcorrecta: "platano",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/cocina/taza.png--taza--cocina",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/banio/cepillo.png--inodoro--bano",
        "assets/images/banio/labavo.png--lavabo--bano",
        "assets/images/cocina/platano.png--platano--cocina",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
  Cocina(
      id: 6,
      title: "Plato",
      size: 12,
      image: "assets/images/cocina/plato.png",
      color: Color(0xFFAEAEAE),
      imagen: "assets/images/cocina/accion/6.jpg",
      mostrar: "En la mesa hay un --",
      opciones: [
        "manzana",
        "toalla",
        "lampara",
        "taza",
        "plato",
        "sandia",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/toalla.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/sandia.png",
      ],
      correcta: "plato",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/inodoro.png--inodoro",
      ],
      objeto: "el plato",
      imgcorrecta: "plato",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/cucahra.png--cuchara--cocina",
        "assets/images/banio/cepillo.png--inodoro--bano",
        "assets/images/cocina/fresa.png--fresa--cocina",
        "assets/images/banio/labavo.png--lavabo--bano",
        "assets/images/cocina/plato.png--plato--cocina",
      ],
      validos: 3,
      lugar: "cocina",
      frase: "la cocina ",
      imglugar: "assets/images/cocina2.gif"),
];