import 'package:flutter/material.dart';

class Recamara {
  final String image, title,imagen,mostrar,correcta;
  final int size, id;
  final Color color;
  final List<String> opciones,imagenes;
  Recamara({
    this.id,
    this.image,
    this.title,
    this.size,
    this.color,
    this.imagen,
    this.mostrar,
    this.imagenes,
    this.opciones,
    this.correcta
  });
}
List<Recamara> objetos = [
  Recamara(
      id: 1,
      title: "Almohada",
      size: 12,
      image: "assets/images/recamara/almohada.png",
      color: Color(0xFF3D82AE),
      imagen: "assets/images/recamara/accion/1.jpg",
      mostrar: "Ruben usa una -- para dormir",
      opciones: [
        "sandia",
        "jabon ",
        "almohada",
        "taza",
        "plato",
        "cepillo dental",
      ],
      imagenes: [
        "assets/images/cocina/sandia.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/almohada.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/platano.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "almohada",
  ),
  Recamara(
      id: 2,
      title: "Armario",
      size: 8,
      image: "assets/images/recamara/armario.png",
      color: Color(0xFFD3A984),
      imagen: "assets/images/recamara/accion/2.jpg",
      // el espacion donde ira la palabra se indica como --
      mostrar: "Karla guarda su ropa en el --",
      opciones: [
        "brocoli",
        "pasta dental",
        "inodoro",
        "taza",
        "plato",
        "armario",
      ],
      imagenes: [
        "assets/images/cocina/brocoli.png",
        "assets/images/banio/pasta.png",
        "assets/images/banio/inodoro.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/recamara/armario.png",
      ],
      correcta: "armario",
  ),
  Recamara(
      id: 3,
      title: "Cama",
      size: 10,
      image: "assets/images/recamara/cama.png",
      color: Color(0xFF989493),
      imagen: "assets/images/recamara/accion/3.jpg",
      mostrar: "Hector está durmiendo en la --",
      opciones: [
        "platano",
        "cama",
        "espejo",
        "taza",
        "plato",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/platano.png",
        "assets/images/recamara/cama.png",
        "assets/images/recamara/espejo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "cama",
  ),
  Recamara(
      id: 4,
      title: "Cobija",
      size: 11,
      image: "assets/images/recamara/cobertor.png",
      color: Color(0xFFE6B398),
      imagen: "assets/images/recamara/accion/4.jpg",
      mostrar: "Joaquín tiene frío y se cubre con el --",
      opciones: [
        "lechuga",
        "cobertor",
        "lavabo",
        "taza",
        "platano",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/lechuga.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/banio/lavabo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/sandia.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "cobertor",
  ),
  Recamara(
      id: 5,
      title: "Espejo",
      size: 28,
      image: "assets/images/recamara/espejo.png",
      color: Color(0xFFFB7883),
      imagen: "assets/images/recamara/accion/5.jpg",
      mostrar: "Rosa se peina enfrente del --",
      opciones: [
        "manzana",
        "jabon ",
        "lampara",
        "taza",
        "pasta dental",
        "espejo",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/espejo.png",
      ],
      correcta: "espejo",
  ),
  Recamara(
    id: 6,
    title: "Lampara",
    size: 12,
    image: "assets/images/recamara/lampara.png",
    color: Color(0xFFAEAEAE),
    imagen: "assets/images/recamara/accion/6.jpg",
    mostrar: "Carmen estudia con una --",
    opciones: [
      "uva",
      "shampooo ",
      "cobija",
      "lampara",
      "plato",
      "cuchara",
    ],
    imagenes: [
      "assets/images/cocina/uva.png",
      "assets/images/banio/shampoo.png",
      "assets/images/recamara/cobertor.png",
      "assets/images/recamara/lampara.png",
      "assets/images/recamara/armario.png",
      "assets/images/cocina/cuchara.png",
    ],
    correcta: "lampara",
  ),
];

