import 'package:flutter/material.dart';

class Recamara {
  final String image,
      title,
      imagen,
      mostrar,
      correcta,
      imgcorrecta,
      objeto,
      frase,
      imglugar,
      lugar;
  final int size, id, validos;
  final Color color;
  final List<String> opciones, imagenes, imagenes2, imagenes3;
  Recamara(
      {this.id,
        this.image,
        this.title,
        this.size,
        this.color,
        this.imagen,
        this.mostrar,
        this.imagenes,
        this.imagenes2,
        this.imagenes3,
        this.validos,
        this.lugar,
        this.frase,
        this.imglugar,
        this.opciones,
        this.imgcorrecta,
        this.objeto,
        this.correcta});
}

List<Recamara> objetosRecam = [
  Recamara(
      id: 1,
      title: "Almohada",
      size: 12,
      image: "assets/images/recamara/almohada.png",
      color: Color(0xFF3D82AE),
      imagen: "assets/images/recamara/accion/1.jpg",
      mostrar: "Ruben usa una -- para dormir",
      opciones: [
        "sandia",
        "jabon ",
        "almohada",
        "taza",
        "plato",
        "cepillo dental",
      ],
      imagenes: [
        "assets/images/cocina/sandia.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/almohada.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/platano.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "almohada",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/taza.png--taza",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/inodoro.png--inodoro",
        "assets/images/cocina/fresa.png--fresa",
      ],
      objeto: "la almohada",
      imgcorrecta: "almohada",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/banio/jabon.png--jabon--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 2,
      title: "Armario",
      size: 8,
      image: "assets/images/recamara/armario.png",
      color: Color(0xFFD3A984),
      imagen: "assets/images/recamara/accion/2.jpg",
      // el espacion donde ira la palabra se indica como --
      mostrar: "Karla guarda su ropa en el --",
      opciones: [
        "brocoli",
        "pasta dental",
        "inodoro",
        "taza",
        "plato",
        "armario",
      ],
      imagenes: [
        "assets/images/cocina/brocoli.png",
        "assets/images/banio/pasta.png",
        "assets/images/banio/inodoro.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/recamara/armario.png",
      ],
      correcta: "armario",

      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/platano.png--platano",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/recamara/armario.png-armario",
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/pasta.png--pasta",
      ],
      objeto: "el armario",
      imgcorrecta: "armario",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/banio/cepillo.png--cepillo dental--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/platano.png--platano--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/recamara/armario.png--armario--recamara",
      ],
      validos: 4,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 3,
      title: "Cama",
      size: 10,
      image: "assets/images/recamara/cama.png",
      color: Color(0xFF989493),
      imagen: "assets/images/recamara/accion/3.jpg",
      mostrar: "Hector está durmiendo en la --",
      opciones: [
        "platano",
        "cama",
        "espejo",
        "taza",
        "plato",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/platano.png",
        "assets/images/recamara/cama.png",
        "assets/images/recamara/espejo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/uva.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "cama",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/fresa.png--fresa",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/recamara.png--cama",
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/cocina/platano.png--platano",
      ],
      objeto: "la cama",
      imgcorrecta: "cama",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/banio/jabon.png--jabon--banio",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/platano.png--platano--cocina",
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/recamara/cama.png--cama--cama",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 4,
      title: "Cobija",
      size: 11,
      image: "assets/images/recamara/cobertor.png",
      color: Color(0xFFE6B398),
      imagen: "assets/images/recamara/accion/4.jpg",
      mostrar: "Joaquín tiene frío y se cubre con el --",
      opciones: [
        "lechuga",
        "cobertor",
        "lavabo",
        "taza",
        "platano",
        "uva",
      ],
      imagenes: [
        "assets/images/cocina/lechuga.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/banio/lavabo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/sandia.png",
        "assets/images/cocina/uva.png",
      ],
      correcta: "cobertor",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/lechuga.png--lechuga",
        "assets/images/recamara/cama.png--cama",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/pasta.png--pasta dental",
        "assets/images/cocina/brocoli.png--brocoli",
      ],
      objeto: "el cobertor",
      imgcorrecta: "cobertor",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/banio/cepillo.png--cepillo--banio",
        "assets/images/recamara/lampara.png--lampara--recamara",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/brocoli.png--brocoli--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
      ],
      validos: 4,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 5,
      title: "Espejo",
      size: 28,
      image: "assets/images/recamara/espejo.png",
      color: Color(0xFFFB7883),
      imagen: "assets/images/recamara/accion/5.jpg",
      mostrar: "Rosa se peina enfrente del --",
      opciones: [
        "manzana",
        "jabon ",
        "lampara",
        "taza",
        "pasta dental",
        "espejo",
      ],
      imagenes: [
        "assets/images/cocina/manzana.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/espejo.png",
      ],
      correcta: "espejo",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/sandia.png--sandia",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/taza.png--taza",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/uva.png--uva",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/toalla.png--toalla",
        "assets/images/cocina/fresa.png--fresa",
      ],
      objeto: "el espejo",
      imgcorrecta: "espejo",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/banio/cepillo.png--cepillo--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/uva.png--uva--cocina",
        "assets/images/recamara/espejo.png--espejo--recamara",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 6,
      title: "Lampara",
      size: 12,
      image: "assets/images/recamara/lampara.png",
      color: Color(0xFFAEAEAE),
      imagen: "assets/images/recamara/accion/6.jpg",
      mostrar: "Carmen estudia con una --",
      opciones: [
        "uva",
        "shampooo ",
        "cobija",
        "lampara",
        "plato",
        "cuchara",
      ],
      imagenes: [
        "assets/images/cocina/uva.png",
        "assets/images/banio/shampoo.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/recamara/lampara.png",
        "assets/images/recamara/armario.png",
        "assets/images/cocina/cuchara.png",
      ],
      correcta: "lampara",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/brocoli.png--brocoli",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/cocina/taza.png--taza",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/manzana.png--manzana",
        "assets/images/banio/pasta.png--pasta dental",
        "assets/images/banio/inodoro.png--inodoro",
        "assets/images/cocina/fresa.png--fresa",
      ],
      objeto: "la almohada",
      imgcorrecta: "lampara",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/banio/shampoo.png--shampoo--banio",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/platano.png--platano--cocina",
        "assets/images/recamara/lampara.png--lamapra--recamara",
        "assets/images/cocina/taza.png--taza--cocina",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
];