import 'package:flutter/material.dart';

class Recamara {
  final String image,
      title,
      imagen,
      mostrar,
      correcta,
      imgcorrecta,
      objeto,
      frase,
      imglugar,
      lugar;
  final int size, id, validos;
  final Color color;
  final List<String> opciones, imagenes, imagenes2, imagenes3;
  Recamara(
      {this.id,
        this.image,
        this.title,
        this.size,
        this.color,
        this.imagen,
        this.mostrar,
        this.imagenes,
        this.imagenes2,
        this.imagenes3,
        this.validos,
        this.lugar,
        this.frase,
        this.imglugar,
        this.opciones,
        this.imgcorrecta,
        this.objeto,
        this.correcta});
}

List<Recamara> objetosRecam = [
  Recamara(
      id: 1,
      title: "Almohada",
      size: 12,
      image: "assets/images/recamara/almohada.png",
      color: Color(0xFF01A2C6),
      imagen: "assets/images/recamara/accion/1.jpg",
      mostrar: "Ruben usa una -- para dormir",
      opciones: [
        "cazuela",
        "jabon ",
        "almohada",
        "taza",
        "plato",
        "cepillo dental",
      ],
      imagenes: [
        "assets/images/cocina/cazuela.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/almohada.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/vaso.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "almohada",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/inodoro.png--inodoro",
        "assets/images/cocina/taza.png--taza",
      ],
      objeto: "la almohada",
      imgcorrecta: "almohada",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/banio/jabon.png--jabon--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 2,
      title: "Armario",
      size: 8,
      image: "assets/images/recamara/armario.png",
      color: Color(0xFFD15A05),
      imagen: "assets/images/recamara/accion/2.jpg",
      // el espacion donde ira la palabra se indica como --
      mostrar: "Karla guarda su ropa en el --",
      opciones: [
        "cazuela",
        "pasta dental",
        "inodoro",
        "taza",
        "plato",
        "armario",
      ],
      imagenes: [
        "assets/images/cocina/cazuela.png",
        "assets/images/banio/pasta.png",
        "assets/images/banio/inodoro.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/recamara/armario.png",
      ],
      correcta: "armario",

      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/vaso.png--vaso",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/taza.png--taza",
        "assets/images/recamara/armario.png--armario",
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/cocina/cazuela.png--cazuela",
        "assets/images/banio/pasta.png--pasta",
      ],
      objeto: "el armario",
      imgcorrecta: "armario",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/banio/cepillo.png--cepillo dental--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/vaso.png--vaso--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/recamara/armario.png--armario--recamara",
      ],
      validos: 4,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 3,
      title: "Cama",
      size: 10,
      image: "assets/images/recamara/cama.png",
      color: Color(0xFF953d68),
      imagen: "assets/images/recamara/accion/3.jpg",
      mostrar: "Hector está durmiendo en la --",
      opciones: [
        "vaso",
        "cama",
        "espejo",
        "taza",
        "plato",
        "estufa",
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/recamara/cama.png",
        "assets/images/recamara/espejo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/plato.png",
        "assets/images/cocina/estufa.png",
        "assets/images/banio/cepillo.png",
      ],
      correcta: "cama",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/cocina/taza.png--taza",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/recamara/cama.png--cama",
        "assets/images/banio/labavo.png--lavabo",
        "assets/images/cocina/vaso.png--vaso",
      ],
      objeto: "la cama",
      imgcorrecta:"cama",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/banio/jabon.png--jabon--banio",
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/cocina/vaso.png--vaso--cocina",
        "assets/images/recamara/espejo.png--espejo--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 4,
      title: "Cobija",
      size: 11,
      image: "assets/images/recamara/cobertor.png",
      color: Color(0xFFf9AC34),
      imagen: "assets/images/recamara/accion/4.jpg",
      mostrar: "Joaquín tiene frío y se cubre con el --",
      opciones: [
        "mesa",
        "cobertor",
        "lavabo",
        "taza",
        "vaso",
        "estufa",
      ],
      imagenes: [
        "assets/images/cocina/mesa.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/banio/labavo.png",
        "assets/images/cocina/taza.png",
        "assets/images/cocina/cazuela.png",
        "assets/images/cocina/estufa.png",
      ],
      correcta: "cobertor",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/plato.png--plato",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/recamara/cama.png--cama",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/pasta.png--pasta dental",
        "assets/images/cocina/cazuela.png--cazuela",
      ],
      objeto: "el cobertor",
      imgcorrecta: "cobertor",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/banio/cepillo.png--cepillo--banio",
        "assets/images/recamara/lampara.png--lampara--recamara",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/cazuela.png--cazuela--cocina",
        "assets/images/recamara/cama.png--cama--recamara",
      ],
      validos: 4,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 5,
      title: "Espejo",
      size: 28,
      image: "assets/images/recamara/espejo.png",
      color: Color(0xFFad2c34),
      imagen: "assets/images/recamara/accion/5.jpg",
      mostrar: "Rosa se peina enfrente del --",
      opciones: [
        "vaso",
        "jabon ",
        "lampara",
        "taza",
        "pasta dental",
        "espejo",
      ],
      imagenes: [
        "assets/images/cocina/vaso.png",
        "assets/images/banio/jabon.png",
        "assets/images/recamara/lampara.png",
        "assets/images/cocina/taza.png",
        "assets/images/banio/pasta.png",
        "assets/images/recamara/espejo.png",
      ],
      correcta: "espejo",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/cazuela.png--cazuela",
        "assets/images/banio/pasta.png--pasta",
        "assets/images/recamara/cobertor.png--cobertor",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/recamara/espejo.png--espejo",
        "assets/images/cocina/estufa.png--estufa",
        "assets/images/banio/cepillo.png--cepillo dental",
        "assets/images/banio/toalla.png--toalla",
        "assets/images/cocina/taza.png--taza",
      ],
      objeto: "el espejo",
      imgcorrecta: "espejo",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/banio/cepillo.png--cepillo--banio",
        "assets/images/recamara/cama.png--cama--recamara",
        "assets/images/cocina/plato.png--plato--cocina",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/estufa.png--estufa--cocina",
        "assets/images/recamara/espejo.png--espejo--recamara",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
  Recamara(
      id: 6,
      title: "Lampara",
      size: 12,
      image: "assets/images/recamara/lampara.png",
      color: Color(0xFF205134),
      imagen: "assets/images/recamara/accion/6.jpg",
      mostrar: "Carmen estudia con una --",
      opciones: [
        "estufa",
        "shampooo ",
        "cobija",
        "lampara",
        "plato",
        "mesa",
      ],
      imagenes: [
        "assets/images/cocina/estufa.png",
        "assets/images/banio/shampoo.png",
        "assets/images/recamara/cobertor.png",
        "assets/images/recamara/lampara.png",
        "assets/images/recamara/armario.png",
        "assets/images/cocina/mesa.png",
      ],
      correcta: "lampara",
      //////////Juego Tobjetos/////
      imagenes2: [
        "assets/images/cocina/cazuela.png--cazuela",
        "assets/images/recamara/lampara.png--lampara",
        "assets/images/banio/shampoo.png--shampoo",
        "assets/images/cocina/mesa.png--mesa",
        "assets/images/recamara/almohada.png--almohada",
        "assets/images/cocina/vaso.png--vaso",
        "assets/images/banio/pasta.png--pasta dental",
        "assets/images/banio/inodoro.png--inodoro",
        "assets/images/cocina/taza.png--taza",
      ],
      objeto: "la almohada",
      imgcorrecta: "lampara",
      ///////////////////juego AdondePertenecen////////////////
      imagenes3: [
        "assets/images/recamara/cobertor.png--cobertor--recamara",
        "assets/images/banio/shampoo.png--shampoo--banio",
        "assets/images/recamara/almohada.png--almohada--recamara",
        "assets/images/cocina/vaso.png--vaso--cocina",
        "assets/images/recamara/lampara.png--lampara--recamara",
        "assets/images/cocina/taza.png--taza--cocina",
      ],
      validos: 3,
      lugar: "recamara",
      frase: "la recamara ",
      imglugar: "assets/images/recamara2.gif"),
];